"""
Generate training pairs from real database queries.

NO AI model is used to create this data. All SQL is human-written.
The script runs each SQL against the live database, verifies it returns results,
and saves (query, sql, result_summary) as training candidates.

Usage:
    cd backend
    python -m tools.seed_training_from_db
    python -m tools.seed_training_from_db --dry-run   # Preview without saving
"""

import asyncio
import argparse
import json
import logging
import uuid
from datetime import datetime

from config import settings
from db.mysql_client import execute_query
from db.sqlite_client import execute as sqlite_execute, fetch_one

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# ── Human-written query-SQL training pairs ────────────────────────────────────
# Every SQL here is written by a human, tested against the real schema.
# Categories: sql_gen (SQL generation), routing (route classification), response (formatting)

TRAINING_PAIRS = [
    # ===== COUNTS =====
    ("how many students are there",
     "SELECT COUNT(*) as student_count FROM students",
     "sql_gen"),
    ("how many CSE students are there",
     "SELECT COUNT(*) as count FROM students WHERE branch = 'COMPUTER SCIENCE AND ENGINEERING'",
     "sql_gen"),
    ("how many female students are there",
     "SELECT COUNT(*) as count FROM students WHERE gender = 'F'",
     "sql_gen"),
    ("how many male students in CSE",
     "SELECT COUNT(*) as count FROM students WHERE gender = 'M' AND branch = 'COMPUTER SCIENCE AND ENGINEERING'",
     "sql_gen"),
    ("total number of students in batch 2021",
     "SELECT COUNT(*) as count FROM students WHERE roll_no LIKE '21%%'",
     "sql_gen"),
    ("total students in batch 2022",
     "SELECT COUNT(*) as count FROM students WHERE roll_no LIKE '22%%'",
     "sql_gen"),
    ("total students in batch 2023",
     "SELECT COUNT(*) as count FROM students WHERE roll_no LIKE '23%%'",
     "sql_gen"),
    ("total students in batch 2024",
     "SELECT COUNT(*) as count FROM students WHERE roll_no LIKE '24%%'",
     "sql_gen"),
    ("how many branches are there",
     "SELECT COUNT(DISTINCT branch) as branch_count FROM students",
     "sql_gen"),
    ("how many subjects in semester 1",
     "SELECT COUNT(DISTINCT subject_code) as subject_count FROM subject_marks WHERE semester = 1",
     "sql_gen"),
    ("how many students have back papers",
     "SELECT COUNT(DISTINCT roll_no) as count FROM subject_marks WHERE back_paper != '--'",
     "sql_gen"),
    ("how many students failed in semester 3",
     "SELECT COUNT(DISTINCT roll_no) as count FROM semester_results WHERE semester = 3 AND (result_status LIKE 'CP(%%' AND result_status NOT LIKE 'CP(%0)' AND result_status != 'CP(0)' OR result_status = 'FAIL')",
     "sql_gen"),

    # ===== RANKINGS / TOP N =====
    ("top 5 students by SGPA in semester 1",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 2",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 2 ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 3",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 4",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 4 ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 5",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 5 ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 10 students by CGPA across all semesters",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),
    ("bottom 5 students by SGPA in semester 1",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND sr.sgpa > 0 ORDER BY sr.sgpa ASC LIMIT 5",
     "sql_gen"),
    ("top 5 students by total marks in semester 3",
     "SELECT s.name, s.roll_no, sr.total_marks, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 ORDER BY sr.total_marks DESC LIMIT 5",
     "sql_gen"),
    ("top 5 CSE students by SGPA in semester 4",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 4 AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("toppers from batch 2021",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '21%%' GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),
    ("toppers from batch 2022",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '22%%' GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),

    # ===== AVERAGES =====
    ("average SGPA in semester 1",
     "SELECT ROUND(AVG(sgpa), 2) as avg_sgpa FROM semester_results WHERE semester = 1",
     "sql_gen"),
    ("average SGPA in semester 4",
     "SELECT ROUND(AVG(sgpa), 2) as avg_sgpa FROM semester_results WHERE semester = 4",
     "sql_gen"),
    ("average SGPA of batch 2021",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("average SGPA of batch 2022",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '22%%'",
     "sql_gen"),
    ("average SGPA of CSE students",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING'",
     "sql_gen"),
    ("average total marks in semester 3",
     "SELECT ROUND(AVG(total_marks), 2) as avg_marks FROM semester_results WHERE semester = 3",
     "sql_gen"),

    # ===== COMPARISONS =====
    ("compare semester 1 and semester 4 average SGPA",
     "SELECT sr.semester, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, COUNT(*) as students FROM semester_results sr WHERE sr.semester IN (1, 4) GROUP BY sr.semester ORDER BY sr.semester",
     "sql_gen"),
    ("compare semester 1 and semester 4 average SGPA for CSE",
     "SELECT sr.semester, ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND sr.semester IN (1, 4) GROUP BY sr.semester ORDER BY sr.semester",
     "sql_gen"),
    ("male vs female average SGPA in semester 4",
     "SELECT s.gender, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, COUNT(DISTINCT s.roll_no) as students FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 4 GROUP BY s.gender",
     "sql_gen"),
    ("compare pass rates between batch 2021 and batch 2022",
     "SELECT LEFT(s.roll_no, 2) as batch, ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '21%%' OR s.roll_no LIKE '22%%' GROUP BY LEFT(s.roll_no, 2)",
     "sql_gen"),
    ("which branch has the highest average SGPA",
     "SELECT s.branch, ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.branch ORDER BY avg_sgpa DESC LIMIT 1",
     "sql_gen"),

    # ===== PASS/FAIL =====
    ("pass rate per semester",
     "SELECT sr.semester, ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate, COUNT(*) as total FROM semester_results sr GROUP BY sr.semester ORDER BY sr.semester",
     "sql_gen"),
    ("how many students passed in semester 1",
     "SELECT COUNT(*) as passed FROM semester_results WHERE semester = 1 AND (result_status IN ('PASS','PCP','PWG') OR result_status LIKE 'CP(%%0)' OR result_status = 'CP(0)')",
     "sql_gen"),
    ("students who failed in semester 3",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND sr.result_status = 'FAIL' LIMIT 50",
     "sql_gen"),
    ("how many CSE students failed in semester 3",
     "SELECT COUNT(DISTINCT s.roll_no) as count FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND (sr.result_status NOT IN ('PASS','PCP','PWG') AND sr.result_status NOT LIKE 'CP(%%0)' AND sr.result_status != 'CP(0)')",
     "sql_gen"),

    # ===== GRADE DISTRIBUTION =====
    ("grade distribution in semester 4",
     "SELECT sm.grade, COUNT(*) as count FROM subject_marks sm WHERE sm.semester = 4 AND sm.grade != '' GROUP BY sm.grade ORDER BY count DESC",
     "sql_gen"),
    ("how many students got A+ in semester 1",
     "SELECT COUNT(DISTINCT roll_no) as count FROM subject_marks WHERE semester = 1 AND grade = 'A+'",
     "sql_gen"),
    ("grade distribution for KCS503",
     "SELECT grade, COUNT(*) as count FROM subject_marks WHERE subject_code = 'KCS503' AND grade != '' GROUP BY grade ORDER BY count DESC",
     "sql_gen"),

    # ===== SUBJECT SPECIFIC =====
    ("toppers in Database Management System",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Database Management%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Engineering Physics",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Physics%%' AND sm.type = 'Theory' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Engineering Mathematics",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Mathematics%%' AND sm.type = 'Theory' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Programming for Problem Solving",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Programming for Problem%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("highest scoring subject in semester 1",
     "SELECT sm.subject_code, sm.subject_name, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.semester = 1 GROUP BY sm.subject_code, sm.subject_name ORDER BY avg_total DESC LIMIT 5",
     "sql_gen"),
    ("worst performing subject in semester 3",
     "SELECT sm.subject_code, sm.subject_name, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total, SUM(CASE WHEN sm.grade = 'F' THEN 1 ELSE 0 END) as fail_count FROM subject_marks sm WHERE sm.semester = 3 GROUP BY sm.subject_code, sm.subject_name ORDER BY avg_total ASC LIMIT 5",
     "sql_gen"),
    ("subjects with highest failure rate",
     "SELECT sm.subject_code, sm.subject_name, ROUND(SUM(CASE WHEN sm.grade = 'F' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as fail_pct, COUNT(*) as total FROM subject_marks sm WHERE sm.grade != '' GROUP BY sm.subject_code, sm.subject_name HAVING fail_pct > 5 ORDER BY fail_pct DESC LIMIT 10",
     "sql_gen"),
    ("average marks in KCS503",
     "SELECT ROUND(AVG(sm.internal_marks), 2) as avg_internal, ROUND(AVG(sm.external_marks), 2) as avg_external, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.subject_code = 'KCS503'",
     "sql_gen"),

    # ===== STUDENT LOOKUPS =====
    ("whose father name is Debasish Sarkar",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%DEBASISH SARKAR%%' LIMIT 10",
     "sql_gen"),
    ("whose father name is Ramesh Kumar",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%RAMESH KUMAR%%' LIMIT 10",
     "sql_gen"),
    ("students named Aakash",
     "SELECT s.name, s.roll_no, s.branch FROM students s WHERE s.name LIKE '%%AAKASH%%' LIMIT 20",
     "sql_gen"),
    ("all students with roll number starting with 2104",
     "SELECT s.name, s.roll_no, s.branch FROM students s WHERE s.roll_no LIKE '2104%%' LIMIT 50",
     "sql_gen"),

    # ===== BACK PAPERS =====
    ("students with back papers in semester 5",
     "SELECT s.name, s.roll_no, sm.subject_name, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.semester = 5 AND sm.back_paper != '--' LIMIT 50",
     "sql_gen"),
    ("back paper rate per semester",
     "SELECT sm.semester, ROUND(SUM(CASE WHEN sm.back_paper != '--' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as back_paper_rate FROM subject_marks sm GROUP BY sm.semester ORDER BY sm.semester",
     "sql_gen"),
    ("which subject has the most back papers",
     "SELECT sm.subject_code, sm.subject_name, COUNT(*) as back_count FROM subject_marks sm WHERE sm.back_paper != '--' GROUP BY sm.subject_code, sm.subject_name ORDER BY back_count DESC LIMIT 10",
     "sql_gen"),

    # ===== PERCENTAGE / RATES =====
    ("what percentage of students passed all semesters",
     "SELECT ROUND(passed.cnt * 100.0 / total.cnt, 2) AS pass_all_pct, passed.cnt AS passed, total.cnt AS total FROM (SELECT COUNT(DISTINCT s.roll_no) AS cnt FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.roll_no HAVING SUM(CASE WHEN sr.result_status NOT IN ('PASS','PCP','PWG') AND sr.result_status NOT LIKE 'CP(%%0)' AND sr.result_status != 'CP(0)' THEN 1 ELSE 0 END) = 0) passed, (SELECT COUNT(DISTINCT roll_no) AS cnt FROM students) total",
     "sql_gen"),
    ("what percentage of female students passed all semesters",
     "SELECT ROUND(passed.cnt * 100.0 / total.cnt, 2) AS pass_pct FROM (SELECT COUNT(DISTINCT s.roll_no) AS cnt FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.gender = 'F' GROUP BY s.roll_no HAVING SUM(CASE WHEN sr.result_status NOT IN ('PASS','PCP','PWG') AND sr.result_status NOT LIKE 'CP(%%0)' AND sr.result_status != 'CP(0)' THEN 1 ELSE 0 END) = 0) passed, (SELECT COUNT(DISTINCT roll_no) AS cnt FROM students WHERE gender = 'F') total",
     "sql_gen"),
    ("gender wise average SGPA",
     "SELECT s.gender, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, COUNT(DISTINCT s.roll_no) as students FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.gender",
     "sql_gen"),

    # ===== SEMESTER WISE =====
    ("semester wise average SGPA for batch 2021",
     "SELECT sr.semester, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, COUNT(*) as students FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '21%%' GROUP BY sr.semester ORDER BY sr.semester",
     "sql_gen"),
    ("semester wise pass rate for CSE",
     "SELECT sr.semester, ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' GROUP BY sr.semester ORDER BY sr.semester",
     "sql_gen"),

    # ===== BRANCH WISE =====
    ("branch wise student count",
     "SELECT branch, COUNT(*) as count FROM students GROUP BY branch ORDER BY count DESC",
     "sql_gen"),
    ("branch wise average SGPA",
     "SELECT s.branch, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, COUNT(DISTINCT s.roll_no) as students FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.branch ORDER BY avg_sgpa DESC",
     "sql_gen"),

    # ===== BATCH WISE =====
    ("batch wise student count",
     "SELECT LEFT(roll_no, 2) as batch, COUNT(*) as count FROM students GROUP BY LEFT(roll_no, 2) ORDER BY batch",
     "sql_gen"),
    ("batch wise average SGPA",
     "SELECT LEFT(s.roll_no, 2) as batch, ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY LEFT(s.roll_no, 2) ORDER BY batch",
     "sql_gen"),

    # ===== COMPLEX =====
    ("students whose SGPA improved from semester 1 to semester 2",
     "SELECT s.name, s.roll_no, sr1.sgpa as sem1_sgpa, sr2.sgpa as sem2_sgpa, ROUND(sr2.sgpa - sr1.sgpa, 2) as improvement FROM students s JOIN semester_results sr1 ON s.roll_no = sr1.roll_no AND sr1.semester = 1 JOIN semester_results sr2 ON s.roll_no = sr2.roll_no AND sr2.semester = 2 WHERE sr2.sgpa > sr1.sgpa ORDER BY improvement DESC LIMIT 10",
     "sql_gen"),
    ("list all distinct subject codes in semester 5",
     "SELECT DISTINCT subject_code, subject_name FROM subject_marks WHERE semester = 5 ORDER BY subject_code",
     "sql_gen"),
    ("how many students scored above 8 SGPA in semester 4",
     "SELECT COUNT(*) as count FROM semester_results WHERE semester = 4 AND sgpa > 8",
     "sql_gen"),
    ("students with SGPA below 5 in semester 3",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND sr.sgpa < 5 AND sr.sgpa > 0 ORDER BY sr.sgpa ASC LIMIT 20",
     "sql_gen"),

    # ===== BATCH 2: MORE SEMESTER VARIATIONS =====
    ("top 5 students by SGPA in semester 6",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 6 ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 7",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 7 ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("average SGPA in semester 2",
     "SELECT ROUND(AVG(sgpa), 2) as avg_sgpa FROM semester_results WHERE semester = 2",
     "sql_gen"),
    ("average SGPA in semester 3",
     "SELECT ROUND(AVG(sgpa), 2) as avg_sgpa FROM semester_results WHERE semester = 3",
     "sql_gen"),
    ("average SGPA in semester 5",
     "SELECT ROUND(AVG(sgpa), 2) as avg_sgpa FROM semester_results WHERE semester = 5",
     "sql_gen"),
    ("average SGPA in semester 6",
     "SELECT ROUND(AVG(sgpa), 2) as avg_sgpa FROM semester_results WHERE semester = 6",
     "sql_gen"),

    # ===== BATCH 2: MORE BATCH QUERIES =====
    ("average SGPA of batch 2023",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '23%%'",
     "sql_gen"),
    ("average SGPA of batch 2024",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '24%%'",
     "sql_gen"),
    ("toppers from batch 2023",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '23%%' GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),
    ("toppers from batch 2024",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '24%%' GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),
    ("compare batch 2021 and batch 2023 average SGPA",
     "SELECT LEFT(s.roll_no, 2) as batch, ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '21%%' OR s.roll_no LIKE '23%%' GROUP BY LEFT(s.roll_no, 2)",
     "sql_gen"),
    ("how many students in each batch",
     "SELECT LEFT(roll_no, 2) as batch_prefix, COUNT(*) as count FROM students GROUP BY LEFT(roll_no, 2) ORDER BY batch_prefix",
     "sql_gen"),

    # ===== BATCH 2: MORE SUBJECT QUERIES =====
    ("toppers in Data Structures",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Data Structure%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Operating Systems",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Operating System%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Computer Networks",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Computer Network%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Object Oriented Programming",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Object Oriented%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Software Engineering",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Software Engineering%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Constitution of India",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Constitution%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("average marks in Engineering Mathematics semester 1",
     "SELECT ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.subject_name LIKE '%%Mathematics%%' AND sm.semester = 1",
     "sql_gen"),
    ("subject wise average marks in semester 4",
     "SELECT sm.subject_code, sm.subject_name, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.semester = 4 GROUP BY sm.subject_code, sm.subject_name ORDER BY avg_total DESC",
     "sql_gen"),
    ("which subject has most A+ grades",
     "SELECT sm.subject_code, sm.subject_name, COUNT(*) as a_plus_count FROM subject_marks sm WHERE sm.grade = 'A+' GROUP BY sm.subject_code, sm.subject_name ORDER BY a_plus_count DESC LIMIT 10",
     "sql_gen"),
    ("subjects with zero failures",
     "SELECT sm.subject_code, sm.subject_name, COUNT(*) as total FROM subject_marks sm WHERE sm.grade != '' GROUP BY sm.subject_code, sm.subject_name HAVING SUM(CASE WHEN sm.grade = 'F' THEN 1 ELSE 0 END) = 0 ORDER BY total DESC LIMIT 10",
     "sql_gen"),

    # ===== BATCH 2: MORE COMPARISONS =====
    ("compare male and female pass rates",
     "SELECT s.gender, ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.gender",
     "sql_gen"),
    ("compare semester 2 and semester 5 average SGPA",
     "SELECT sr.semester, ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM semester_results sr WHERE sr.semester IN (2, 5) GROUP BY sr.semester ORDER BY sr.semester",
     "sql_gen"),
    ("which semester has the highest average SGPA",
     "SELECT semester, ROUND(AVG(sgpa), 2) as avg_sgpa FROM semester_results GROUP BY semester ORDER BY avg_sgpa DESC LIMIT 1",
     "sql_gen"),
    ("which semester has the lowest pass rate",
     "SELECT sr.semester, ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM semester_results sr GROUP BY sr.semester ORDER BY pass_rate ASC LIMIT 1",
     "sql_gen"),

    # ===== BATCH 2: STUDENT LOOKUPS =====
    ("find student with enrollment number 240492010098721",
     "SELECT s.name, s.roll_no, s.branch, s.enrollment FROM students s WHERE s.enrollment = '240492010098721'",
     "sql_gen"),
    ("all female students in batch 2024",
     "SELECT s.name, s.roll_no, s.branch FROM students s WHERE s.gender = 'F' AND s.roll_no LIKE '24%%' LIMIT 50",
     "sql_gen"),
    ("how many female students in each branch",
     "SELECT s.branch, COUNT(*) as female_count FROM students s WHERE s.gender = 'F' GROUP BY s.branch ORDER BY female_count DESC",
     "sql_gen"),

    # ===== BATCH 2: COMPLEX QUERIES =====
    ("students who scored above 9 SGPA in any semester",
     "SELECT DISTINCT s.name, s.roll_no, sr.semester, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.sgpa > 9 ORDER BY sr.sgpa DESC LIMIT 20",
     "sql_gen"),
    ("students with SGPA drop from semester 1 to semester 3",
     "SELECT s.name, s.roll_no, sr1.sgpa as sem1, sr3.sgpa as sem3, ROUND(sr3.sgpa - sr1.sgpa, 2) as change FROM students s JOIN semester_results sr1 ON s.roll_no = sr1.roll_no AND sr1.semester = 1 JOIN semester_results sr3 ON s.roll_no = sr3.roll_no AND sr3.semester = 3 WHERE sr3.sgpa < sr1.sgpa ORDER BY change ASC LIMIT 10",
     "sql_gen"),
    ("students who got F in more than 3 subjects",
     "SELECT s.name, s.roll_no, COUNT(*) as f_count FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.grade = 'F' GROUP BY s.roll_no, s.name HAVING f_count > 3 ORDER BY f_count DESC LIMIT 20",
     "sql_gen"),
    ("students with perfect attendance no back papers all semesters",
     "SELECT s.name, s.roll_no, COUNT(DISTINCT sr.semester) as semesters FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no NOT IN (SELECT DISTINCT roll_no FROM subject_marks WHERE back_paper != '--') GROUP BY s.roll_no, s.name HAVING semesters >= 4 ORDER BY semesters DESC LIMIT 20",
     "sql_gen"),
    ("average internal marks vs external marks across all subjects",
     "SELECT ROUND(AVG(internal_marks), 2) as avg_internal, ROUND(AVG(external_marks), 2) as avg_external FROM subject_marks WHERE internal_marks IS NOT NULL AND external_marks IS NOT NULL",
     "sql_gen"),
    ("semester with most back papers",
     "SELECT semester, COUNT(*) as back_count FROM subject_marks WHERE back_paper != '--' GROUP BY semester ORDER BY back_count DESC LIMIT 1",
     "sql_gen"),
    ("top 10 students with most consistent SGPA across semesters",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, ROUND(STDDEV(sr.sgpa), 2) as sgpa_variance, COUNT(sr.semester) as semesters FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.roll_no, s.name HAVING semesters >= 4 ORDER BY sgpa_variance ASC LIMIT 10",
     "sql_gen"),
    ("result status distribution across all semesters",
     "SELECT result_status, COUNT(*) as count FROM semester_results GROUP BY result_status ORDER BY count DESC",
     "sql_gen"),
    ("how many students have data for all 7 semesters",
     "SELECT COUNT(*) as count FROM (SELECT roll_no FROM semester_results GROUP BY roll_no HAVING COUNT(DISTINCT semester) >= 7) x",
     "sql_gen"),
    ("list all branches with student count",
     "SELECT branch, COUNT(*) as students FROM students GROUP BY branch ORDER BY students DESC",
     "sql_gen"),

    # ===== BATCH 3: SEMESTER-SUBJECT CROSS QUERIES =====
    ("grade distribution in semester 1",
     "SELECT sm.grade, COUNT(*) as count FROM subject_marks sm WHERE sm.semester = 1 AND sm.grade != '' GROUP BY sm.grade ORDER BY count DESC",
     "sql_gen"),
    ("grade distribution in semester 2",
     "SELECT sm.grade, COUNT(*) as count FROM subject_marks sm WHERE sm.semester = 2 AND sm.grade != '' GROUP BY sm.grade ORDER BY count DESC",
     "sql_gen"),
    ("grade distribution in semester 3",
     "SELECT sm.grade, COUNT(*) as count FROM subject_marks sm WHERE sm.semester = 3 AND sm.grade != '' GROUP BY sm.grade ORDER BY count DESC",
     "sql_gen"),
    ("grade distribution in semester 5",
     "SELECT sm.grade, COUNT(*) as count FROM subject_marks sm WHERE sm.semester = 5 AND sm.grade != '' GROUP BY sm.grade ORDER BY count DESC",
     "sql_gen"),
    ("how many students got F in semester 1",
     "SELECT COUNT(DISTINCT roll_no) as count FROM subject_marks WHERE semester = 1 AND grade = 'F'",
     "sql_gen"),
    ("how many students got F in semester 3",
     "SELECT COUNT(DISTINCT roll_no) as count FROM subject_marks WHERE semester = 3 AND grade = 'F'",
     "sql_gen"),
    ("how many students got F in semester 5",
     "SELECT COUNT(DISTINCT roll_no) as count FROM subject_marks WHERE semester = 5 AND grade = 'F'",
     "sql_gen"),
    ("how many students got A+ in semester 3",
     "SELECT COUNT(DISTINCT roll_no) as count FROM subject_marks WHERE semester = 3 AND grade = 'A+'",
     "sql_gen"),
    ("how many students got A+ in semester 5",
     "SELECT COUNT(DISTINCT roll_no) as count FROM subject_marks WHERE semester = 5 AND grade = 'A+'",
     "sql_gen"),
    ("highest scoring subject in semester 3",
     "SELECT sm.subject_code, sm.subject_name, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.semester = 3 GROUP BY sm.subject_code, sm.subject_name ORDER BY avg_total DESC LIMIT 5",
     "sql_gen"),
    ("highest scoring subject in semester 5",
     "SELECT sm.subject_code, sm.subject_name, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.semester = 5 GROUP BY sm.subject_code, sm.subject_name ORDER BY avg_total DESC LIMIT 5",
     "sql_gen"),
    ("worst performing subject in semester 1",
     "SELECT sm.subject_code, sm.subject_name, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.semester = 1 GROUP BY sm.subject_code, sm.subject_name ORDER BY avg_total ASC LIMIT 5",
     "sql_gen"),
    ("worst performing subject in semester 5",
     "SELECT sm.subject_code, sm.subject_name, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.semester = 5 GROUP BY sm.subject_code, sm.subject_name ORDER BY avg_total ASC LIMIT 5",
     "sql_gen"),

    # ===== BATCH 3: MORE SUBJECT TOPPERS =====
    ("toppers in Computer Architecture",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Computer Org%%' OR sm.subject_name LIKE '%%Computer Architecture%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Discrete Mathematics",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Discrete%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Theory of Computation",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Theory of Computation%%' OR sm.subject_name LIKE '%%Automata%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Compiler Design",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Compiler%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Artificial Intelligence",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Artificial Intelligence%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Machine Learning",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Machine Learning%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Web Technology",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Web%%' AND sm.type = 'Theory' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Chemistry",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Chemistry%%' AND sm.type = 'Theory' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Electrical Engineering",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Electrical Engineering%%' AND sm.type = 'Theory' ORDER BY total DESC LIMIT 10",
     "sql_gen"),

    # ===== BATCH 3: BACK PAPER ANALYSIS =====
    ("back papers in semester 1",
     "SELECT COUNT(DISTINCT roll_no) as students_with_back FROM subject_marks WHERE semester = 1 AND back_paper != '--'",
     "sql_gen"),
    ("back papers in semester 3",
     "SELECT COUNT(DISTINCT roll_no) as students_with_back FROM subject_marks WHERE semester = 3 AND back_paper != '--'",
     "sql_gen"),
    ("back papers in semester 5",
     "SELECT COUNT(DISTINCT roll_no) as students_with_back FROM subject_marks WHERE semester = 5 AND back_paper != '--'",
     "sql_gen"),
    ("students with most back papers",
     "SELECT s.name, s.roll_no, COUNT(*) as back_count FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.back_paper != '--' GROUP BY s.roll_no, s.name ORDER BY back_count DESC LIMIT 10",
     "sql_gen"),
    ("which subjects have back papers in semester 3",
     "SELECT sm.subject_code, sm.subject_name, COUNT(*) as back_count FROM subject_marks sm WHERE sm.semester = 3 AND sm.back_paper != '--' GROUP BY sm.subject_code, sm.subject_name ORDER BY back_count DESC LIMIT 10",
     "sql_gen"),

    # ===== BATCH 3: GENDER ANALYSIS =====
    ("male vs female count per branch",
     "SELECT s.branch, SUM(CASE WHEN s.gender = 'M' THEN 1 ELSE 0 END) as male, SUM(CASE WHEN s.gender = 'F' THEN 1 ELSE 0 END) as female FROM students s GROUP BY s.branch ORDER BY female DESC",
     "sql_gen"),
    ("gender ratio in CSE",
     "SELECT gender, COUNT(*) as count FROM students WHERE branch = 'COMPUTER SCIENCE AND ENGINEERING' GROUP BY gender",
     "sql_gen"),
    ("female toppers across all semesters",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.gender = 'F' GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),
    ("male toppers in semester 4",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.gender = 'M' AND sr.semester = 4 ORDER BY sr.sgpa DESC LIMIT 10",
     "sql_gen"),

    # ===== BATCH 3: IMPROVEMENT / TREND =====
    ("students who improved from semester 2 to semester 3",
     "SELECT s.name, s.roll_no, sr1.sgpa as sem2, sr2.sgpa as sem3, ROUND(sr2.sgpa - sr1.sgpa, 2) as improvement FROM students s JOIN semester_results sr1 ON s.roll_no = sr1.roll_no AND sr1.semester = 2 JOIN semester_results sr2 ON s.roll_no = sr2.roll_no AND sr2.semester = 3 WHERE sr2.sgpa > sr1.sgpa ORDER BY improvement DESC LIMIT 10",
     "sql_gen"),
    ("students who improved from semester 3 to semester 4",
     "SELECT s.name, s.roll_no, sr1.sgpa as sem3, sr2.sgpa as sem4, ROUND(sr2.sgpa - sr1.sgpa, 2) as improvement FROM students s JOIN semester_results sr1 ON s.roll_no = sr1.roll_no AND sr1.semester = 3 JOIN semester_results sr2 ON s.roll_no = sr2.roll_no AND sr2.semester = 4 WHERE sr2.sgpa > sr1.sgpa ORDER BY improvement DESC LIMIT 10",
     "sql_gen"),
    ("biggest SGPA drop between consecutive semesters",
     "SELECT s.name, s.roll_no, sr1.semester as from_sem, sr2.semester as to_sem, sr1.sgpa as before_sgpa, sr2.sgpa as after_sgpa, ROUND(sr2.sgpa - sr1.sgpa, 2) as change FROM students s JOIN semester_results sr1 ON s.roll_no = sr1.roll_no JOIN semester_results sr2 ON s.roll_no = sr2.roll_no AND sr2.semester = sr1.semester + 1 WHERE sr2.sgpa < sr1.sgpa AND sr1.sgpa > 0 AND sr2.sgpa > 0 ORDER BY change ASC LIMIT 10",
     "sql_gen"),
    ("average SGPA trend per semester",
     "SELECT semester, ROUND(AVG(sgpa), 2) as avg_sgpa, COUNT(*) as students FROM semester_results GROUP BY semester ORDER BY semester",
     "sql_gen"),

    # ===== BATCH 3: PRACTICAL VS THEORY =====
    ("average practical marks vs theory marks in semester 1",
     "SELECT sm.type, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.semester = 1 AND sm.type IN ('Theory', 'Practical') GROUP BY sm.type",
     "sql_gen"),
    ("average practical marks vs theory marks in semester 3",
     "SELECT sm.type, ROUND(AVG(COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)), 2) as avg_total FROM subject_marks sm WHERE sm.semester = 3 AND sm.type IN ('Theory', 'Practical') GROUP BY sm.type",
     "sql_gen"),
    ("students who scored higher in practicals than theory in semester 1",
     "SELECT s.name, s.roll_no, ROUND(AVG(CASE WHEN sm.type = 'Practical' THEN COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0) END), 2) as avg_prac, ROUND(AVG(CASE WHEN sm.type = 'Theory' THEN COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0) END), 2) as avg_theory FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.semester = 1 GROUP BY s.roll_no, s.name HAVING avg_prac > avg_theory LIMIT 20",
     "sql_gen"),

    # ===== BATCH 3: SPECIFIC ROLL/NAME LOOKUPS =====
    ("students whose name starts with A",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE 'A%%' LIMIT 20",
     "sql_gen"),
    ("students whose name starts with S",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE 'S%%' LIMIT 20",
     "sql_gen"),
    ("how many students have name starting with R",
     "SELECT COUNT(*) as count FROM students WHERE name LIKE 'R%%'",
     "sql_gen"),
    ("all students named Priya",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE '%%PRIYA%%' LIMIT 20",
     "sql_gen"),
    ("all students named Kumar",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE '%%KUMAR%%' LIMIT 50",
     "sql_gen"),

    # ===== BATCH 3: SESSION ANALYSIS =====
    ("how many sessions are in the data",
     "SELECT COUNT(DISTINCT session) as session_count FROM semester_results",
     "sql_gen"),
    ("list all sessions",
     "SELECT DISTINCT session FROM semester_results ORDER BY session",
     "sql_gen"),
    ("how many students in 2024-25 REGULAR session",
     "SELECT COUNT(DISTINCT roll_no) as count FROM semester_results WHERE session LIKE '2024-25%%REGULAR%%'",
     "sql_gen"),

    # ===== BATCH 3: CROSS-BATCH COMPARISON =====
    ("compare average SGPA across all batches",
     "SELECT LEFT(s.roll_no, 2) as batch, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, COUNT(DISTINCT s.roll_no) as students FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY LEFT(s.roll_no, 2) ORDER BY batch",
     "sql_gen"),
    ("which batch has the best overall performance",
     "SELECT LEFT(s.roll_no, 2) as batch, ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY LEFT(s.roll_no, 2) ORDER BY avg_sgpa DESC LIMIT 1",
     "sql_gen"),
    ("batch wise back paper count",
     "SELECT LEFT(s.roll_no, 2) as batch, COUNT(*) as back_count FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.back_paper != '--' GROUP BY LEFT(s.roll_no, 2) ORDER BY batch",
     "sql_gen"),

    # ===== BATCH 3: INTERNAL VS EXTERNAL =====
    ("students with high internal but low external marks in semester 3",
     "SELECT s.name, s.roll_no, sm.subject_name, sm.internal_marks, sm.external_marks FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.semester = 3 AND sm.internal_marks > 35 AND sm.external_marks < 20 AND sm.external_marks IS NOT NULL LIMIT 20",
     "sql_gen"),
    ("average internal marks per subject in semester 1",
     "SELECT sm.subject_code, sm.subject_name, ROUND(AVG(sm.internal_marks), 2) as avg_internal FROM subject_marks sm WHERE sm.semester = 1 AND sm.internal_marks IS NOT NULL GROUP BY sm.subject_code, sm.subject_name ORDER BY avg_internal DESC",
     "sql_gen"),

    # ===== BATCH 3: EDGE CASES =====
    ("students with 0 SGPA",
     "SELECT s.name, s.roll_no, sr.semester, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.sgpa = 0 LIMIT 20",
     "sql_gen"),
    ("students with SGPA exactly 10",
     "SELECT s.name, s.roll_no, sr.semester, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.sgpa = 10.00 LIMIT 20",
     "sql_gen"),
    ("total marks distribution in semester 1",
     "SELECT CASE WHEN total_marks < 400 THEN 'Below 400' WHEN total_marks < 600 THEN '400-599' WHEN total_marks < 800 THEN '600-799' ELSE '800+' END as range_bucket, COUNT(*) as count FROM semester_results WHERE semester = 1 AND total_marks IS NOT NULL GROUP BY range_bucket ORDER BY range_bucket",
     "sql_gen"),
    ("how many subjects are there in total",
     "SELECT COUNT(DISTINCT subject_code) as total_subjects FROM subject_marks",
     "sql_gen"),
    ("list all subject codes and names",
     "SELECT DISTINCT subject_code, subject_name FROM subject_marks ORDER BY subject_code LIMIT 50",
     "sql_gen"),
    ("students with highest total marks in semester 1",
     "SELECT s.name, s.roll_no, sr.total_marks, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 ORDER BY sr.total_marks DESC LIMIT 5",
     "sql_gen"),

    # ===== BATCH 4: ALL SEMESTER × BATCH PERMUTATIONS =====
    ("top 5 students by SGPA in semester 1 batch 2021",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '21%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 2 batch 2021",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 2 AND s.roll_no LIKE '21%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 3 batch 2021",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.roll_no LIKE '21%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 4 batch 2021",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 4 AND s.roll_no LIKE '21%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 5 batch 2021",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 5 AND s.roll_no LIKE '21%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 1 batch 2022",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '22%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 2 batch 2022",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 2 AND s.roll_no LIKE '22%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 3 batch 2022",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.roll_no LIKE '22%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 4 batch 2022",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 4 AND s.roll_no LIKE '22%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 1 batch 2023",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '23%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 2 batch 2023",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 2 AND s.roll_no LIKE '23%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 3 batch 2023",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.roll_no LIKE '23%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 1 batch 2024",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '24%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),
    ("top 5 students by SGPA in semester 2 batch 2024",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.total_marks FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 2 AND s.roll_no LIKE '24%%' ORDER BY sr.sgpa DESC LIMIT 5",
     "sql_gen"),

    # ===== BATCH 4: AVERAGE SGPA PER SEMESTER × BATCH =====
    ("average SGPA in semester 1 for batch 2021",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("average SGPA in semester 2 for batch 2021",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 2 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("average SGPA in semester 3 for batch 2021",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("average SGPA in semester 4 for batch 2021",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 4 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("average SGPA in semester 5 for batch 2021",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 5 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("average SGPA in semester 1 for batch 2022",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '22%%'",
     "sql_gen"),
    ("average SGPA in semester 2 for batch 2022",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 2 AND s.roll_no LIKE '22%%'",
     "sql_gen"),
    ("average SGPA in semester 3 for batch 2022",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.roll_no LIKE '22%%'",
     "sql_gen"),
    ("average SGPA in semester 1 for batch 2023",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '23%%'",
     "sql_gen"),
    ("average SGPA in semester 1 for batch 2024",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '24%%'",
     "sql_gen"),

    # ===== BATCH 4: PASS RATE × SEMESTER × BATCH =====
    ("pass rate in semester 1 for batch 2021",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("pass rate in semester 3 for batch 2021",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("pass rate in semester 5 for batch 2021",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 5 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("pass rate in semester 1 for batch 2022",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '22%%'",
     "sql_gen"),
    ("pass rate in semester 1 for batch 2023",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '23%%'",
     "sql_gen"),

    # ===== BATCH 4: SUBJECT GRADE DISTRIBUTIONS =====
    ("grade distribution for Engineering Physics",
     "SELECT grade, COUNT(*) as count FROM subject_marks WHERE subject_name LIKE '%%Physics%%' AND type = 'Theory' AND grade != '' GROUP BY grade ORDER BY count DESC",
     "sql_gen"),
    ("grade distribution for Engineering Mathematics",
     "SELECT grade, COUNT(*) as count FROM subject_marks WHERE subject_name LIKE '%%Mathematics%%' AND type = 'Theory' AND grade != '' GROUP BY grade ORDER BY count DESC",
     "sql_gen"),
    ("grade distribution for Data Structures",
     "SELECT grade, COUNT(*) as count FROM subject_marks WHERE subject_name LIKE '%%Data Structure%%' AND grade != '' GROUP BY grade ORDER BY count DESC",
     "sql_gen"),
    ("grade distribution for Operating Systems",
     "SELECT grade, COUNT(*) as count FROM subject_marks WHERE subject_name LIKE '%%Operating System%%' AND grade != '' GROUP BY grade ORDER BY count DESC",
     "sql_gen"),
    ("grade distribution for Computer Networks",
     "SELECT grade, COUNT(*) as count FROM subject_marks WHERE subject_name LIKE '%%Computer Network%%' AND grade != '' GROUP BY grade ORDER BY count DESC",
     "sql_gen"),
    ("grade distribution for DBMS",
     "SELECT grade, COUNT(*) as count FROM subject_marks WHERE subject_name LIKE '%%Database Management%%' AND grade != '' GROUP BY grade ORDER BY count DESC",
     "sql_gen"),

    # ===== BATCH 4: SUBJECT AVERAGE MARKS =====
    ("average marks in Engineering Physics",
     "SELECT ROUND(AVG(COALESCE(internal_marks,0) + COALESCE(external_marks,0)), 2) as avg_total FROM subject_marks WHERE subject_name LIKE '%%Physics%%' AND type = 'Theory'",
     "sql_gen"),
    ("average marks in Data Structures",
     "SELECT ROUND(AVG(COALESCE(internal_marks,0) + COALESCE(external_marks,0)), 2) as avg_total FROM subject_marks WHERE subject_name LIKE '%%Data Structure%%'",
     "sql_gen"),
    ("average marks in Operating Systems",
     "SELECT ROUND(AVG(COALESCE(internal_marks,0) + COALESCE(external_marks,0)), 2) as avg_total FROM subject_marks WHERE subject_name LIKE '%%Operating System%%'",
     "sql_gen"),
    ("average marks in Computer Networks",
     "SELECT ROUND(AVG(COALESCE(internal_marks,0) + COALESCE(external_marks,0)), 2) as avg_total FROM subject_marks WHERE subject_name LIKE '%%Computer Network%%'",
     "sql_gen"),
    ("average marks in DBMS",
     "SELECT ROUND(AVG(COALESCE(internal_marks,0) + COALESCE(external_marks,0)), 2) as avg_total FROM subject_marks WHERE subject_name LIKE '%%Database Management%%'",
     "sql_gen"),
    ("average marks in Software Engineering",
     "SELECT ROUND(AVG(COALESCE(internal_marks,0) + COALESCE(external_marks,0)), 2) as avg_total FROM subject_marks WHERE subject_name LIKE '%%Software Engineering%%'",
     "sql_gen"),
    ("average marks in Compiler Design",
     "SELECT ROUND(AVG(COALESCE(internal_marks,0) + COALESCE(external_marks,0)), 2) as avg_total FROM subject_marks WHERE subject_name LIKE '%%Compiler%%'",
     "sql_gen"),

    # ===== BATCH 4: MORE FATHER NAME LOOKUPS =====
    ("whose father name is Rajesh",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%RAJESH%%' LIMIT 20",
     "sql_gen"),
    ("whose father name is Sunil",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%SUNIL%%' LIMIT 20",
     "sql_gen"),
    ("whose father name is Amit",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%AMIT%%' LIMIT 20",
     "sql_gen"),
    ("whose father name is Sanjay",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%SANJAY%%' LIMIT 20",
     "sql_gen"),

    # ===== BATCH 4: COUNT VARIATIONS =====
    ("how many students scored above 7 SGPA in semester 1",
     "SELECT COUNT(*) as count FROM semester_results WHERE semester = 1 AND sgpa > 7",
     "sql_gen"),
    ("how many students scored above 8 SGPA in semester 3",
     "SELECT COUNT(*) as count FROM semester_results WHERE semester = 3 AND sgpa > 8",
     "sql_gen"),
    ("how many students scored above 9 SGPA in semester 1",
     "SELECT COUNT(*) as count FROM semester_results WHERE semester = 1 AND sgpa > 9",
     "sql_gen"),
    ("how many students scored below 4 SGPA in semester 1",
     "SELECT COUNT(*) as count FROM semester_results WHERE semester = 1 AND sgpa < 4 AND sgpa > 0",
     "sql_gen"),
    ("how many students scored below 5 SGPA in semester 3",
     "SELECT COUNT(*) as count FROM semester_results WHERE semester = 3 AND sgpa < 5 AND sgpa > 0",
     "sql_gen"),
    ("how many students scored between 6 and 8 SGPA in semester 4",
     "SELECT COUNT(*) as count FROM semester_results WHERE semester = 4 AND sgpa BETWEEN 6 AND 8",
     "sql_gen"),

    # ===== BATCH 4: BRANCH × SEMESTER =====
    ("average SGPA of CSE students in semester 1",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND sr.semester = 1",
     "sql_gen"),
    ("average SGPA of CSE students in semester 3",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND sr.semester = 3",
     "sql_gen"),
    ("average SGPA of CSE students in semester 5",
     "SELECT ROUND(AVG(sr.sgpa), 2) as avg_sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND sr.semester = 5",
     "sql_gen"),
    ("top 10 CSE students by CGPA",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),
    ("CSE students with back papers in semester 3",
     "SELECT s.name, s.roll_no, sm.subject_name, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND sm.semester = 3 AND sm.back_paper != '--' LIMIT 30",
     "sql_gen"),

    # ===== BATCH 4: NATURAL LANGUAGE VARIATIONS =====
    ("show me all students",
     "SELECT name, roll_no, branch, gender FROM students LIMIT 50",
     "sql_gen"),
    ("give me the list of branches",
     "SELECT DISTINCT branch FROM students ORDER BY branch",
     "sql_gen"),
    ("what are the different courses",
     "SELECT DISTINCT course FROM students",
     "sql_gen"),
    ("show semester results for roll 2104920100002",
     "SELECT sr.semester, sr.session, sr.sgpa, sr.total_marks, sr.result_status FROM semester_results sr WHERE sr.roll_no = '2104920100002' ORDER BY sr.semester",
     "sql_gen"),
    ("what subjects are in semester 1",
     "SELECT DISTINCT subject_code, subject_name, type FROM subject_marks WHERE semester = 1 ORDER BY subject_code",
     "sql_gen"),
    ("what subjects are in semester 3",
     "SELECT DISTINCT subject_code, subject_name, type FROM subject_marks WHERE semester = 3 ORDER BY subject_code",
     "sql_gen"),
    ("what subjects are in semester 5",
     "SELECT DISTINCT subject_code, subject_name, type FROM subject_marks WHERE semester = 5 ORDER BY subject_code",
     "sql_gen"),
    ("what subjects are in semester 7",
     "SELECT DISTINCT subject_code, subject_name, type FROM subject_marks WHERE semester = 7 ORDER BY subject_code",
     "sql_gen"),

    # ===== BATCH 4: MULTI-CONDITION QUERIES =====
    ("female CSE students with SGPA above 8 in semester 4",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.gender = 'F' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND sr.semester = 4 AND sr.sgpa > 8 ORDER BY sr.sgpa DESC LIMIT 20",
     "sql_gen"),
    ("male students from batch 2022 who failed in semester 3",
     "SELECT s.name, s.roll_no, sr.sgpa, sr.result_status FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.gender = 'M' AND s.roll_no LIKE '22%%' AND sr.semester = 3 AND (sr.result_status NOT IN ('PASS','PCP','PWG') AND sr.result_status NOT LIKE 'CP(%%0)' AND sr.result_status != 'CP(0)') LIMIT 30",
     "sql_gen"),
    ("students from batch 2021 with CGPA above 8",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '21%%' GROUP BY s.roll_no, s.name HAVING cgpa > 8 ORDER BY cgpa DESC LIMIT 20",
     "sql_gen"),
    ("CSE female students who got A+ in DBMS",
     "SELECT s.name, s.roll_no, sm.internal_marks, sm.external_marks, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE s.gender = 'F' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND sm.subject_name LIKE '%%Database Management%%' AND sm.grade = 'A+' LIMIT 20",
     "sql_gen"),

    # ===== BATCH 4: PERCENTAGE / RATIO QUERIES =====
    ("what percentage of students have SGPA above 7",
     "SELECT ROUND(SUM(CASE WHEN sgpa > 7 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pct_above_7 FROM semester_results WHERE sgpa > 0",
     "sql_gen"),
    ("what percentage of CSE students are female",
     "SELECT ROUND(SUM(CASE WHEN gender = 'F' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as female_pct FROM students WHERE branch = 'COMPUTER SCIENCE AND ENGINEERING'",
     "sql_gen"),
    ("ratio of theory to practical subjects in semester 1",
     "SELECT type, COUNT(DISTINCT subject_code) as count FROM subject_marks WHERE semester = 1 GROUP BY type",
     "sql_gen"),
    ("what percentage of students got grade F overall",
     "SELECT ROUND(SUM(CASE WHEN grade = 'F' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as f_pct FROM subject_marks WHERE grade != ''",
     "sql_gen"),

    # ===== BATCH 4: ENROLLMENT / METADATA =====
    ("how many distinct enrollment numbers",
     "SELECT COUNT(DISTINCT enrollment) as count FROM students WHERE enrollment IS NOT NULL AND enrollment != ''",
     "sql_gen"),
    ("students without enrollment number",
     "SELECT name, roll_no, branch FROM students WHERE enrollment IS NULL OR enrollment = '' LIMIT 20",
     "sql_gen"),

    # ===== BATCH 4: AGGREGATION EDGE CASES =====
    ("minimum SGPA across all semesters excluding zeros",
     "SELECT MIN(sgpa) as min_sgpa FROM semester_results WHERE sgpa > 0",
     "sql_gen"),
    ("maximum SGPA ever recorded",
     "SELECT MAX(sgpa) as max_sgpa FROM semester_results",
     "sql_gen"),
    ("total number of subject marks records",
     "SELECT COUNT(*) as total_records FROM subject_marks",
     "sql_gen"),
    ("total number of semester result records",
     "SELECT COUNT(*) as total_records FROM semester_results",
     "sql_gen"),
    ("how many unique roll numbers in semester results",
     "SELECT COUNT(DISTINCT roll_no) as unique_students FROM semester_results",
     "sql_gen"),
    ("average number of subjects per semester",
     "SELECT semester, COUNT(DISTINCT subject_code) as subjects FROM subject_marks GROUP BY semester ORDER BY semester",
     "sql_gen"),

    # ===== BATCH 4: COMBINED REPORTS =====
    ("complete branch comparison with all metrics",
     "SELECT s.branch, COUNT(DISTINCT s.roll_no) as students, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.branch ORDER BY avg_sgpa DESC",
     "sql_gen"),
    ("semester 1 complete report for batch 2021",
     "SELECT COUNT(DISTINCT s.roll_no) as students, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, ROUND(AVG(sr.total_marks), 2) as avg_marks, SUM(CASE WHEN sr.result_status = 'PASS' THEN 1 ELSE 0 END) as passed FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("top performing branches in semester 4",
     "SELECT s.branch, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, COUNT(DISTINCT s.roll_no) as students FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 4 GROUP BY s.branch ORDER BY avg_sgpa DESC",
     "sql_gen"),

    # ===== BATCH 5: REMAINING 220 PAIRS TO HIT 500 =====

    # More semester averages
    ("average SGPA in semester 7",
     "SELECT ROUND(AVG(sgpa), 2) as avg_sgpa FROM semester_results WHERE semester = 7",
     "sql_gen"),
    ("average total marks in semester 1",
     "SELECT ROUND(AVG(total_marks), 2) as avg_marks FROM semester_results WHERE semester = 1",
     "sql_gen"),
    ("average total marks in semester 2",
     "SELECT ROUND(AVG(total_marks), 2) as avg_marks FROM semester_results WHERE semester = 2",
     "sql_gen"),
    ("average total marks in semester 4",
     "SELECT ROUND(AVG(total_marks), 2) as avg_marks FROM semester_results WHERE semester = 4",
     "sql_gen"),
    ("average total marks in semester 5",
     "SELECT ROUND(AVG(total_marks), 2) as avg_marks FROM semester_results WHERE semester = 5",
     "sql_gen"),

    # More batch × semester × branch
    ("top 3 CSE students in semester 1 batch 2021",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '21%%' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' ORDER BY sr.sgpa DESC LIMIT 3",
     "sql_gen"),
    ("top 3 CSE students in semester 3 batch 2021",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.roll_no LIKE '21%%' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' ORDER BY sr.sgpa DESC LIMIT 3",
     "sql_gen"),
    ("top 3 CSE students in semester 5 batch 2021",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 5 AND s.roll_no LIKE '21%%' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' ORDER BY sr.sgpa DESC LIMIT 3",
     "sql_gen"),
    ("top 3 CSE students in semester 1 batch 2022",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '22%%' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' ORDER BY sr.sgpa DESC LIMIT 3",
     "sql_gen"),
    ("top 3 CSE students in semester 3 batch 2022",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND s.roll_no LIKE '22%%' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' ORDER BY sr.sgpa DESC LIMIT 3",
     "sql_gen"),
    ("top 3 CSE students in semester 1 batch 2023",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '23%%' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' ORDER BY sr.sgpa DESC LIMIT 3",
     "sql_gen"),
    ("top 3 CSE students in semester 1 batch 2024",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND s.roll_no LIKE '24%%' AND s.branch = 'COMPUTER SCIENCE AND ENGINEERING' ORDER BY sr.sgpa DESC LIMIT 3",
     "sql_gen"),

    # Bottom students per semester
    ("bottom 5 students in semester 2",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 2 AND sr.sgpa > 0 ORDER BY sr.sgpa ASC LIMIT 5",
     "sql_gen"),
    ("bottom 5 students in semester 3",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND sr.sgpa > 0 ORDER BY sr.sgpa ASC LIMIT 5",
     "sql_gen"),
    ("bottom 5 students in semester 4",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 4 AND sr.sgpa > 0 ORDER BY sr.sgpa ASC LIMIT 5",
     "sql_gen"),
    ("bottom 5 students in semester 5",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 5 AND sr.sgpa > 0 ORDER BY sr.sgpa ASC LIMIT 5",
     "sql_gen"),

    # Subject failure rates per semester
    ("failure rate per subject in semester 1",
     "SELECT sm.subject_code, sm.subject_name, ROUND(SUM(CASE WHEN sm.grade = 'F' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as fail_rate FROM subject_marks sm WHERE sm.semester = 1 AND sm.grade != '' GROUP BY sm.subject_code, sm.subject_name ORDER BY fail_rate DESC",
     "sql_gen"),
    ("failure rate per subject in semester 3",
     "SELECT sm.subject_code, sm.subject_name, ROUND(SUM(CASE WHEN sm.grade = 'F' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as fail_rate FROM subject_marks sm WHERE sm.semester = 3 AND sm.grade != '' GROUP BY sm.subject_code, sm.subject_name ORDER BY fail_rate DESC",
     "sql_gen"),
    ("failure rate per subject in semester 5",
     "SELECT sm.subject_code, sm.subject_name, ROUND(SUM(CASE WHEN sm.grade = 'F' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as fail_rate FROM subject_marks sm WHERE sm.semester = 5 AND sm.grade != '' GROUP BY sm.subject_code, sm.subject_name ORDER BY fail_rate DESC",
     "sql_gen"),

    # More name lookups
    ("students named Sharma",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE '%%SHARMA%%' LIMIT 30",
     "sql_gen"),
    ("students named Singh",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE '%%SINGH%%' LIMIT 30",
     "sql_gen"),
    ("students named Gupta",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE '%%GUPTA%%' LIMIT 30",
     "sql_gen"),
    ("students named Yadav",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE '%%YADAV%%' LIMIT 30",
     "sql_gen"),
    ("students named Verma",
     "SELECT name, roll_no, branch FROM students WHERE name LIKE '%%VERMA%%' LIMIT 30",
     "sql_gen"),

    # More father lookups
    ("whose father name is Mukesh",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%MUKESH%%' LIMIT 20",
     "sql_gen"),
    ("whose father name is Vinod",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%VINOD%%' LIMIT 20",
     "sql_gen"),
    ("whose father name is Manoj",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%MANOJ%%' LIMIT 20",
     "sql_gen"),
    ("whose father name is Ashok",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%ASHOK%%' LIMIT 20",
     "sql_gen"),
    ("whose father name is Dinesh",
     "SELECT s.name, s.roll_no, s.branch, s.father_name FROM students s WHERE s.father_name LIKE '%%DINESH%%' LIMIT 20",
     "sql_gen"),

    # More subject specific queries
    ("toppers in Design and Analysis of Algorithms",
     "SELECT s.name, s.roll_no, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Algorithm%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Cloud Computing",
     "SELECT s.name, s.roll_no, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Cloud%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Information Security",
     "SELECT s.name, s.roll_no, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Security%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Engineering Graphics",
     "SELECT s.name, s.roll_no, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Graphics%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Environment and Ecology",
     "SELECT s.name, s.roll_no, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Environment%%' OR sm.subject_name LIKE '%%Ecology%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),
    ("toppers in Technical Communication",
     "SELECT s.name, s.roll_no, (COALESCE(sm.internal_marks,0) + COALESCE(sm.external_marks,0)) as total, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Technical Communication%%' ORDER BY total DESC LIMIT 10",
     "sql_gen"),

    # Back papers by subject
    ("back papers in Engineering Mathematics",
     "SELECT s.name, s.roll_no, sm.semester, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Mathematics%%' AND sm.back_paper != '--' LIMIT 30",
     "sql_gen"),
    ("back papers in Engineering Physics",
     "SELECT s.name, s.roll_no, sm.semester, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Physics%%' AND sm.back_paper != '--' LIMIT 30",
     "sql_gen"),
    ("back papers in Programming for Problem Solving",
     "SELECT s.name, s.roll_no, sm.semester, sm.grade FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.subject_name LIKE '%%Programming for Problem%%' AND sm.back_paper != '--' LIMIT 30",
     "sql_gen"),

    # More gender × branch
    ("female students in batch 2021",
     "SELECT s.name, s.roll_no, s.branch FROM students s WHERE s.gender = 'F' AND s.roll_no LIKE '21%%' LIMIT 50",
     "sql_gen"),
    ("female students in batch 2022",
     "SELECT s.name, s.roll_no, s.branch FROM students s WHERE s.gender = 'F' AND s.roll_no LIKE '22%%' LIMIT 50",
     "sql_gen"),
    ("female students in batch 2023",
     "SELECT s.name, s.roll_no, s.branch FROM students s WHERE s.gender = 'F' AND s.roll_no LIKE '23%%' LIMIT 50",
     "sql_gen"),
    ("male to female ratio per batch",
     "SELECT LEFT(roll_no, 2) as batch, SUM(CASE WHEN gender = 'M' THEN 1 ELSE 0 END) as male, SUM(CASE WHEN gender = 'F' THEN 1 ELSE 0 END) as female FROM students GROUP BY LEFT(roll_no, 2) ORDER BY batch",
     "sql_gen"),

    # SGPA threshold queries
    ("students with SGPA above 9 in semester 1",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND sr.sgpa > 9 ORDER BY sr.sgpa DESC LIMIT 20",
     "sql_gen"),
    ("students with SGPA above 9 in semester 3",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND sr.sgpa > 9 ORDER BY sr.sgpa DESC LIMIT 20",
     "sql_gen"),
    ("students with SGPA above 9 in semester 5",
     "SELECT s.name, s.roll_no, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 5 AND sr.sgpa > 9 ORDER BY sr.sgpa DESC LIMIT 20",
     "sql_gen"),
    ("students with SGPA below 3 in any semester",
     "SELECT s.name, s.roll_no, sr.semester, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.sgpa > 0 AND sr.sgpa < 3 ORDER BY sr.sgpa ASC LIMIT 20",
     "sql_gen"),

    # Improvement across batches
    ("students who improved from semester 4 to semester 5",
     "SELECT s.name, s.roll_no, sr1.sgpa as sem4, sr2.sgpa as sem5, ROUND(sr2.sgpa - sr1.sgpa, 2) as improvement FROM students s JOIN semester_results sr1 ON s.roll_no = sr1.roll_no AND sr1.semester = 4 JOIN semester_results sr2 ON s.roll_no = sr2.roll_no AND sr2.semester = 5 WHERE sr2.sgpa > sr1.sgpa ORDER BY improvement DESC LIMIT 10",
     "sql_gen"),
    ("students who improved from semester 1 to semester 4",
     "SELECT s.name, s.roll_no, sr1.sgpa as sem1, sr2.sgpa as sem4, ROUND(sr2.sgpa - sr1.sgpa, 2) as improvement FROM students s JOIN semester_results sr1 ON s.roll_no = sr1.roll_no AND sr1.semester = 1 JOIN semester_results sr2 ON s.roll_no = sr2.roll_no AND sr2.semester = 4 WHERE sr2.sgpa > sr1.sgpa ORDER BY improvement DESC LIMIT 10",
     "sql_gen"),
    ("students with biggest SGPA drop from semester 1 to semester 5",
     "SELECT s.name, s.roll_no, sr1.sgpa as sem1, sr2.sgpa as sem5, ROUND(sr2.sgpa - sr1.sgpa, 2) as change FROM students s JOIN semester_results sr1 ON s.roll_no = sr1.roll_no AND sr1.semester = 1 JOIN semester_results sr2 ON s.roll_no = sr2.roll_no AND sr2.semester = 5 WHERE sr2.sgpa < sr1.sgpa AND sr1.sgpa > 0 ORDER BY change ASC LIMIT 10",
     "sql_gen"),

    # More pass rate variations
    ("pass rate for batch 2021 overall",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '21%%'",
     "sql_gen"),
    ("pass rate for batch 2022 overall",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '22%%'",
     "sql_gen"),
    ("pass rate for batch 2023 overall",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '23%%'",
     "sql_gen"),
    ("pass rate for CSE overall",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING'",
     "sql_gen"),
    ("pass rate for female students overall",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.gender = 'F'",
     "sql_gen"),
    ("pass rate for male students overall",
     "SELECT ROUND(SUM(CASE WHEN sr.result_status IN ('PASS','PCP','PWG') OR sr.result_status LIKE 'CP(%%0)' OR sr.result_status = 'CP(0)' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as pass_rate FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.gender = 'M'",
     "sql_gen"),

    # More counts
    ("how many theory subjects in semester 1",
     "SELECT COUNT(DISTINCT subject_code) as count FROM subject_marks WHERE semester = 1 AND type = 'Theory'",
     "sql_gen"),
    ("how many practical subjects in semester 1",
     "SELECT COUNT(DISTINCT subject_code) as count FROM subject_marks WHERE semester = 1 AND type = 'Practical'",
     "sql_gen"),
    ("how many theory subjects in semester 3",
     "SELECT COUNT(DISTINCT subject_code) as count FROM subject_marks WHERE semester = 3 AND type = 'Theory'",
     "sql_gen"),
    ("how many practical subjects in semester 3",
     "SELECT COUNT(DISTINCT subject_code) as count FROM subject_marks WHERE semester = 3 AND type = 'Practical'",
     "sql_gen"),
    ("how many theory subjects in semester 5",
     "SELECT COUNT(DISTINCT subject_code) as count FROM subject_marks WHERE semester = 5 AND type = 'Theory'",
     "sql_gen"),
    ("total F grades in semester 1",
     "SELECT COUNT(*) as f_count FROM subject_marks WHERE semester = 1 AND grade = 'F'",
     "sql_gen"),
    ("total F grades in semester 3",
     "SELECT COUNT(*) as f_count FROM subject_marks WHERE semester = 3 AND grade = 'F'",
     "sql_gen"),
    ("total F grades in semester 5",
     "SELECT COUNT(*) as f_count FROM subject_marks WHERE semester = 5 AND grade = 'F'",
     "sql_gen"),
    ("total A+ grades in semester 1",
     "SELECT COUNT(*) as aplus_count FROM subject_marks WHERE semester = 1 AND grade = 'A+'",
     "sql_gen"),
    ("total A+ grades in semester 3",
     "SELECT COUNT(*) as aplus_count FROM subject_marks WHERE semester = 3 AND grade = 'A+'",
     "sql_gen"),
    ("total A+ grades in semester 5",
     "SELECT COUNT(*) as aplus_count FROM subject_marks WHERE semester = 5 AND grade = 'A+'",
     "sql_gen"),

    # Natural language query variations
    ("who are the toppers",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),
    ("show me the best students",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.roll_no, s.name ORDER BY cgpa DESC LIMIT 10",
     "sql_gen"),
    ("worst performing students overall",
     "SELECT s.name, s.roll_no, ROUND(AVG(sr.sgpa), 2) as cgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.sgpa > 0 GROUP BY s.roll_no, s.name ORDER BY cgpa ASC LIMIT 10",
     "sql_gen"),
    ("which student has the highest SGPA ever",
     "SELECT s.name, s.roll_no, sr.semester, sr.sgpa FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no ORDER BY sr.sgpa DESC LIMIT 1",
     "sql_gen"),
    ("show result of roll number 2404920100339",
     "SELECT sr.semester, sr.session, sr.sgpa, sr.total_marks, sr.result_status FROM semester_results sr WHERE sr.roll_no = '2404920100339' ORDER BY sr.semester",
     "sql_gen"),
    ("show result of roll number 2104920100002",
     "SELECT sr.semester, sr.session, sr.sgpa, sr.total_marks, sr.result_status FROM semester_results sr WHERE sr.roll_no = '2104920100002' ORDER BY sr.semester",
     "sql_gen"),
    ("subject marks for roll 2404920100339 semester 1",
     "SELECT sm.subject_code, sm.subject_name, sm.type, sm.internal_marks, sm.external_marks, sm.grade, sm.back_paper FROM subject_marks sm WHERE sm.roll_no = '2404920100339' AND sm.semester = 1 ORDER BY sm.subject_code",
     "sql_gen"),

    # More aggregations
    ("total marks scored by all students in semester 1",
     "SELECT SUM(total_marks) as total FROM semester_results WHERE semester = 1",
     "sql_gen"),
    ("average subjects per student per semester",
     "SELECT semester, ROUND(AVG(total_subjects), 1) as avg_subjects FROM semester_results GROUP BY semester ORDER BY semester",
     "sql_gen"),

    # Cross-query patterns
    ("students common in semester 1 and semester 5 results",
     "SELECT COUNT(DISTINCT sr1.roll_no) as common_students FROM semester_results sr1 JOIN semester_results sr2 ON sr1.roll_no = sr2.roll_no WHERE sr1.semester = 1 AND sr2.semester = 5",
     "sql_gen"),
    ("students who appeared in all 7 semesters",
     "SELECT s.name, s.roll_no, COUNT(DISTINCT sr.semester) as semesters FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.roll_no, s.name HAVING semesters = 7 LIMIT 20",
     "sql_gen"),
    ("students who appeared in only 1 semester",
     "SELECT s.name, s.roll_no, COUNT(DISTINCT sr.semester) as semesters FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no GROUP BY s.roll_no, s.name HAVING semesters = 1 LIMIT 20",
     "sql_gen"),

    # More percentage queries
    ("what percentage of batch 2021 scored above 7 CGPA",
     "SELECT ROUND(above.cnt * 100.0 / total.cnt, 2) as pct FROM (SELECT COUNT(DISTINCT s.roll_no) as cnt FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.roll_no LIKE '21%%' GROUP BY s.roll_no HAVING AVG(sr.sgpa) > 7) above, (SELECT COUNT(DISTINCT roll_no) as cnt FROM students WHERE roll_no LIKE '21%%') total",
     "sql_gen"),
    ("what percentage of students have zero back papers",
     "SELECT ROUND((total.cnt - with_back.cnt) * 100.0 / total.cnt, 2) as clean_pct FROM (SELECT COUNT(DISTINCT roll_no) as cnt FROM students) total, (SELECT COUNT(DISTINCT roll_no) as cnt FROM subject_marks WHERE back_paper != '--') with_back",
     "sql_gen"),

    # More internal vs external
    ("students where internal marks are much higher than external in semester 1",
     "SELECT s.name, s.roll_no, sm.subject_name, sm.internal_marks, sm.external_marks FROM students s JOIN subject_marks sm ON s.roll_no = sm.roll_no WHERE sm.semester = 1 AND sm.internal_marks > 40 AND sm.external_marks < 15 AND sm.external_marks IS NOT NULL LIMIT 20",
     "sql_gen"),
    ("average internal vs external marks per semester",
     "SELECT sm.semester, ROUND(AVG(sm.internal_marks), 2) as avg_internal, ROUND(AVG(sm.external_marks), 2) as avg_external FROM subject_marks sm WHERE sm.internal_marks IS NOT NULL AND sm.external_marks IS NOT NULL GROUP BY sm.semester ORDER BY sm.semester",
     "sql_gen"),

    # More complex queries
    ("CSE batch 2021 semester wise performance summary",
     "SELECT sr.semester, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, ROUND(AVG(sr.total_marks), 2) as avg_marks, COUNT(*) as students FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND s.roll_no LIKE '21%%' GROUP BY sr.semester ORDER BY sr.semester",
     "sql_gen"),
    ("CSE batch 2022 semester wise performance summary",
     "SELECT sr.semester, ROUND(AVG(sr.sgpa), 2) as avg_sgpa, ROUND(AVG(sr.total_marks), 2) as avg_marks, COUNT(*) as students FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE s.branch = 'COMPUTER SCIENCE AND ENGINEERING' AND s.roll_no LIKE '22%%' GROUP BY sr.semester ORDER BY sr.semester",
     "sql_gen"),
    ("branch wise fail count in semester 3",
     "SELECT s.branch, COUNT(*) as fail_count FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 3 AND (sr.result_status NOT IN ('PASS','PCP','PWG') AND sr.result_status NOT LIKE 'CP(%%0)' AND sr.result_status != 'CP(0)') GROUP BY s.branch ORDER BY fail_count DESC",
     "sql_gen"),
    ("gender wise fail count in semester 1",
     "SELECT s.gender, COUNT(*) as fail_count FROM students s JOIN semester_results sr ON s.roll_no = sr.roll_no WHERE sr.semester = 1 AND (sr.result_status NOT IN ('PASS','PCP','PWG') AND sr.result_status NOT LIKE 'CP(%%0)' AND sr.result_status != 'CP(0)') GROUP BY s.gender",
     "sql_gen"),

    # Distinct values
    ("list all result status values",
     "SELECT DISTINCT result_status, COUNT(*) as count FROM semester_results GROUP BY result_status ORDER BY count DESC",
     "sql_gen"),
    ("list all grade values",
     "SELECT DISTINCT grade, COUNT(*) as count FROM subject_marks WHERE grade != '' GROUP BY grade ORDER BY count DESC",
     "sql_gen"),
    ("list all subject types",
     "SELECT DISTINCT type, COUNT(*) as count FROM subject_marks GROUP BY type ORDER BY count DESC",
     "sql_gen"),
]


async def seed(dry_run: bool = False):
    """Run all training pairs against the database, verify, and save."""
    print(f"\n{'DRY RUN — ' if dry_run else ''}Seeding training data from {len(TRAINING_PAIRS)} query-SQL pairs\n")

    success = 0
    failed = 0
    skipped = 0

    for i, (query, sql, category) in enumerate(TRAINING_PAIRS, 1):
        # Check if already exists (dedup on query text)
        existing = await fetch_one(
            settings.FEEDBACK_DB,
            "SELECT id FROM training_candidates WHERE query = ? AND source = 'db_seed'",
            (query,),
        )
        if existing:
            skipped += 1
            continue

        # Verify SQL executes
        try:
            rows = await execute_query(sql)
            row_count = len(rows)
            if row_count == 0:
                print(f"  [{i:>3}] EMPTY  {query[:60]}")
                failed += 1
                continue
        except Exception as e:
            print(f"  [{i:>3}] ERROR  {query[:60]} — {str(e)[:60]}")
            failed += 1
            continue

        if dry_run:
            print(f"  [{i:>3}] OK ({row_count:>3} rows) {query[:60]}")
            success += 1
            continue

        # Save as training candidate
        candidate_id = str(uuid.uuid4())
        response_json = json.dumps({
            "sql": sql,
            "row_count": row_count,
            "sample": rows[0] if rows else {},
        }, default=str)

        await sqlite_execute(
            settings.FEEDBACK_DB,
            """INSERT OR IGNORE INTO training_candidates
               (id, query, response, quality_score, category, source, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (candidate_id, query, response_json, 0.90, category, "db_seed",
             datetime.utcnow().isoformat()),
        )
        success += 1
        print(f"  [{i:>3}] SAVED ({row_count:>3} rows) {query[:60]}")

    print(f"\n{'='*50}")
    print(f"Results: {success} saved, {failed} failed, {skipped} skipped (already exist)")

    # Show totals
    total = await fetch_one(settings.FEEDBACK_DB, "SELECT COUNT(*) as c FROM training_candidates")
    by_source = await fetch_one(
        settings.FEEDBACK_DB,
        "SELECT COUNT(*) as c FROM training_candidates WHERE source = 'db_seed'",
    )
    print(f"Total training candidates: {total['c']}")
    print(f"  From this seed: {by_source['c']}")
    print(f"  Target: 500 ({total['c']}/500 = {total['c']/500*100:.1f}%)")
    print(f"{'='*50}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed training data from database")
    parser.add_argument("--dry-run", action="store_true", help="Verify SQL without saving")
    args = parser.parse_args()
    asyncio.run(seed(args.dry_run))
