"""
Milvus Collection Setup + Data Insertion for KCCITM AI Assistant.

Creates two collections:
  - student_results: HNSW (dense) + SPARSE_INVERTED_INDEX (BM25) + metadata fields
  - faq:             Same schema pattern, empty (ready for Phase 9)

Data flow:
  1. Load chunks from data/chunks.jsonl
  2. Load embeddings from data/embeddings.jsonl
  3. Match by chunk_id and insert into Milvus
  4. Milvus auto-generates sparse (BM25) vectors from the text field

Usage:
    cd backend
    python -m ingestion.milvus_indexer
"""

import json
import logging
import os
import time
from itertools import islice
from typing import Any, Iterator

from pymilvus import MilvusClient, DataType, Function, FunctionType, AnnSearchRequest, RRFRanker

from config import settings

# ── ANSI colours ─────────────────────────────────────────────────────────────
GREEN  = "\033[92m"
RED    = "\033[91m"
YELLOW = "\033[93m"
RESET  = "\033[0m"

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

DATA_DIR        = "data"
CHUNKS_FILE     = os.path.join(DATA_DIR, "chunks.jsonl")
EMBEDDINGS_FILE = os.path.join(DATA_DIR, "embeddings.jsonl")

BATCH_SIZE  = 500
MAX_RETRIES = 3


# ── Connection helpers ────────────────────────────────────────────────────────

def get_client() -> MilvusClient:
    """Connect to Milvus with retry on connection failure."""
    uri = settings.milvus_uri
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            client = MilvusClient(uri=uri)
            # Ping by listing collections
            client.list_collections()
            logger.info("Connected to Milvus at %s", uri)
            return client
        except Exception as exc:
            if attempt < MAX_RETRIES:
                wait = 2 ** attempt
                print(f"{YELLOW}⚠ Milvus not ready (attempt {attempt}/{MAX_RETRIES}), retrying in {wait}s...{RESET}")
                time.sleep(wait)
            else:
                print(f"{RED}✗ Cannot connect to Milvus at {uri}: {exc}{RESET}")
                raise


# ── Schema builders ───────────────────────────────────────────────────────────

def _build_student_schema(client: MilvusClient):
    """Build the student_results collection schema."""
    schema = client.create_schema(auto_id=False, enable_dynamic_field=False)

    # Primary key
    schema.add_field("chunk_id", DataType.VARCHAR, is_primary=True, max_length=100)

    # Text field — BM25 tokenization enabled
    schema.add_field("text", DataType.VARCHAR, max_length=10000, enable_analyzer=True)

    # Dense vector from nomic-embed-text (768-dim)
    schema.add_field("dense", DataType.FLOAT_VECTOR, dim=settings.OLLAMA_EMBED_DIM)

    # Sparse vector — AUTO-GENERATED by BM25 function from text field
    schema.add_field("sparse", DataType.SPARSE_FLOAT_VECTOR)

    # Metadata fields for filtering
    schema.add_field("roll_no",       DataType.VARCHAR, max_length=50)
    schema.add_field("name",          DataType.VARCHAR, max_length=255)
    schema.add_field("branch",        DataType.VARCHAR, max_length=300)
    schema.add_field("course",        DataType.VARCHAR, max_length=100)
    schema.add_field("semester",      DataType.INT64)
    schema.add_field("sgpa",          DataType.FLOAT)
    schema.add_field("session",       DataType.VARCHAR, max_length=100)
    schema.add_field("result_status", DataType.VARCHAR, max_length=50)
    schema.add_field("gender",        DataType.VARCHAR, max_length=5)

    # BM25 function: auto-converts text → sparse vectors
    schema.add_function(Function(
        name="bm25_fn",
        function_type=FunctionType.BM25,
        input_field_names=["text"],
        output_field_names=["sparse"],
    ))

    return schema


def _build_student_indexes(client: MilvusClient):
    """Build index parameters for the student_results collection."""
    index_params = client.prepare_index_params()

    # Dense vector: AUTOINDEX (milvus-lite compatible; maps to HNSW on full Milvus)
    index_params.add_index(
        field_name="dense",
        index_type="AUTOINDEX",
        metric_type="COSINE",
    )

    # Sparse vector: inverted index for BM25
    index_params.add_index(
        field_name="sparse",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
    )

    return index_params


def _build_faq_schema(client: MilvusClient):
    """Build the FAQ collection schema."""
    schema = client.create_schema(auto_id=False, enable_dynamic_field=False)

    schema.add_field("faq_id",   DataType.VARCHAR, is_primary=True, max_length=100)
    schema.add_field("question", DataType.VARCHAR, max_length=3000, enable_analyzer=True)
    schema.add_field("answer",   DataType.VARCHAR, max_length=10000)
    schema.add_field("dense",    DataType.FLOAT_VECTOR, dim=settings.OLLAMA_EMBED_DIM)
    schema.add_field("sparse",   DataType.SPARSE_FLOAT_VECTOR)

    schema.add_function(Function(
        name="faq_bm25",
        function_type=FunctionType.BM25,
        input_field_names=["question"],
        output_field_names=["sparse"],
    ))

    return schema


def _build_faq_indexes(client: MilvusClient):
    """Build index parameters for the FAQ collection."""
    index_params = client.prepare_index_params()

    index_params.add_index(
        field_name="dense",
        index_type="AUTOINDEX",
        metric_type="COSINE",
    )

    index_params.add_index(
        field_name="sparse",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
    )

    return index_params


# ── Collection management ─────────────────────────────────────────────────────

def create_student_collection(client: MilvusClient) -> None:
    """Drop (if exists) and recreate the student_results collection."""
    name = settings.MILVUS_COLLECTION

    if client.has_collection(name):
        client.drop_collection(name)
        print(f"{YELLOW}⚠ Dropped existing collection '{name}'{RESET}")

    client.create_collection(
        collection_name=name,
        schema=_build_student_schema(client),
        index_params=_build_student_indexes(client),
    )
    print(f"{GREEN}✓ Created collection '{name}' with AUTOINDEX + BM25 indexes{RESET}")


def create_faq_collection(client: MilvusClient) -> None:
    """Drop (if exists) and recreate the empty FAQ collection."""
    name = settings.MILVUS_FAQ_COLLECTION

    if client.has_collection(name):
        client.drop_collection(name)
        print(f"{YELLOW}⚠ Dropped existing FAQ collection '{name}'{RESET}")

    client.create_collection(
        collection_name=name,
        schema=_build_faq_schema(client),
        index_params=_build_faq_indexes(client),
    )
    print(f"{GREEN}✓ Created empty '{name}' collection{RESET}")


# ── Data loading ──────────────────────────────────────────────────────────────

def _load_embeddings(path: str) -> dict[str, list[float]]:
    """Load embeddings from JSONL into a chunk_id → vector dict."""
    emb_map: dict[str, list[float]] = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            obj = json.loads(line)
            emb_map[obj["chunk_id"]] = obj["embedding"]
    return emb_map


def _load_chunks(path: str) -> list[tuple[str, dict]]:
    """Load chunks from JSONL."""
    chunks = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            obj = json.loads(line)
            chunks.append((obj["text"], obj["metadata"]))
    return chunks


def _batched(iterable, n: int) -> Iterator[list]:
    """Yield successive n-sized lists from iterable."""
    it = iter(iterable)
    while True:
        batch = list(islice(it, n))
        if not batch:
            return
        yield batch


# ── Data insertion ────────────────────────────────────────────────────────────

def insert_all_chunks(client: MilvusClient, chunks: list[tuple[str, dict]], emb_map: dict) -> int:
    """
    Insert all chunks into the student_results collection.

    The 'sparse' field is intentionally omitted — Milvus auto-generates it
    via the BM25 function from the 'text' field.

    Returns total number of records inserted.
    """
    collection = settings.MILVUS_COLLECTION
    total = len(chunks)
    inserted = 0
    skipped = 0

    # Build flat list of insert dicts
    records = []
    for text, meta in chunks:
        cid = meta["chunk_id"]
        embedding = emb_map.get(cid)
        if embedding is None:
            skipped += 1
            continue

        records.append({
            "chunk_id":      cid,
            "text":          text[:9990],  # guard against max_length=10000
            "dense":         embedding,
            # sparse is auto-generated — do NOT include it
            "roll_no":       str(meta.get("roll_no", ""))[:49],
            "name":          str(meta.get("name", ""))[:254],
            "branch":        str(meta.get("branch", ""))[:299],
            "course":        str(meta.get("course", ""))[:99],
            "semester":      int(meta.get("semester", 0)),
            "sgpa":          float(meta.get("sgpa", 0.0) or 0.0),
            "session":       str(meta.get("session", ""))[:99],
            "result_status": str(meta.get("result_status", ""))[:49],
            "gender":        str(meta.get("gender", ""))[:4],
        })

    if skipped:
        print(f"{YELLOW}⚠ Skipped {skipped} chunks with missing embeddings{RESET}")

    for batch in _batched(records, BATCH_SIZE):
        client.insert(collection_name=collection, data=batch)
        inserted += len(batch)
        print(f"  Inserted {inserted}/{len(records)} chunks...", end="\r", flush=True)

    print()  # newline after \r progress
    return inserted


# ── Main entry point ──────────────────────────────────────────────────────────

def run_indexer() -> None:
    """Run the full Milvus indexing pipeline."""

    # Validate input files exist
    for path in (CHUNKS_FILE, EMBEDDINGS_FILE):
        if not os.path.exists(path):
            print(f"{RED}✗ Required file not found: {path}{RESET}")
            print("  Run ingestion.chunker and ingestion.embedder first.")
            return

    # Connect
    client = get_client()

    # Step 1: Create student_results collection
    create_student_collection(client)

    # Step 2: Load data
    print("Loading chunks and embeddings...")
    chunks = _load_chunks(CHUNKS_FILE)
    emb_map = _load_embeddings(EMBEDDINGS_FILE)
    print(f"  {len(chunks)} chunks, {len(emb_map)} embeddings loaded")

    # Step 3: Insert data
    start = time.time()
    inserted = insert_all_chunks(client, chunks, emb_map)
    elapsed = time.time() - start

    print(
        f"{GREEN}✓ Milvus indexing complete. "
        f"Total chunks: {inserted} (in {elapsed:.1f}s){RESET}"
    )

    # Step 4: Create empty FAQ collection
    create_faq_collection(client)

    print(f"\n{GREEN}✓ All collections ready:{RESET}")
    for col in [settings.MILVUS_COLLECTION, settings.MILVUS_FAQ_COLLECTION]:
        stats = client.get_collection_stats(col)
        print(f"  {col}: {stats.get('row_count', 0)} entities")


if __name__ == "__main__":
    run_indexer()
